##################
# Setting defaults

CLOUDFLARE_EMAIL="${CLOUDFLARE_EMAIL:-$EMAIL}"

RENEW_DAYS_BEFORE_EXPIRE="${RENEW_DAYS_BEFORE_EXPIRE:-30}"
GIT_COMMITS="${GIT_COMMITS:-yes}"
DRY_RUN="${DRY_RUN:-no}"
DISABLED="${DISABLED:-no}"
ENVIRONMENT="${ENVIRONMENT:-staging}"

KEY_TYPE="${KEY_TYPE:-rsa2048}"
